import type { NextPage } from "next";
import { useEffect } from "react";
import Head from "next/head";
import axios from "axios";

import Navbar from "../components/Navbar";

const API_KEY = "47aca678a38ce417df5a2be5f2fc98a6";

const Home: NextPage = () => {
  // useEffect(() => {
  //   const serverStatusUrl = `https://api.mozambiquehe.re/servers?auth=${API_KEY}`;
  //   axios.get(serverStatusUrl).then((res) => {
  //     console.log(res);
  //   });
  // }, []);

  return (
    <>
      <Head>
        <title>Apex Monitor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet"/> 
      </Head>
      <Navbar/>
      <h1>Welcome to Apex Legends!</h1>
      <footer>Powered by Fubocas.com</footer>
    </>
  );
};

export default Home;
