import Head from "next/head";
import React, { useEffect, useState } from "react";
import Navbar from "../components/Navbar/Navbar";
import PlayerSearch from "../components/PlayerSearch/PlayerSearch";
import SearchInput from "../components/SearchInput/SearchInput";

import styles from "../styles/Home.module.css";

const PlayerStatistics = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Apex Monitor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <h1 className={styles.title}>Search for user here</h1>
        <PlayerSearch />
      </main>

      <footer className={styles.footer}>Powered by Goys.com</footer>
    </div>
  );
};

export default PlayerStatistics;
